spring:
  datasource:
    online:
      name: online
#      jdbc-url: jdbc:mysql://rm-2zegp2rq5w4aw24xpjo.mysql.rds.aliyuncs.com:3306/ljcj?useSSL=false
      jdbc-url: jdbc:mysql://rm-2zegp2rq5w4aw24xp.mysql.rds.aliyuncs.com:3306/ljcj?useSSL=false
      username: linjiao
      password: Ljcj!2#4
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    test:
      name: test
      jdbc-url: jdbc:mysql://39.105.156.56:3306/ljcj?useSSL=false
      username: root
      password: Ljcj-1201
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.lj.cmslive.model  # 注意：对应实体类的路径

#日志相关配置
logging:
  level:
    root : info
  file: log\\log.log
